export enum ESvg {
  add = 'add',
  delete = 'delete',
  error = 'error',
  ready = 'ready',
  search = 'search',
  warning = 'warning',
  youtube = 'youtube',
  telegram = 'telegram',
  instagram = 'instagram',
  light = 'light',
  dark = 'dark',
  arrow = 'arrow',
  sad = 'sad',
}
